apiVersion: apps/v1
kind: Deployment 
metadata:
  name: webapp

spec:
  selector:
    # manage any pod with specified label
    matchLabels:
      app: webapp
  # no. of replicas of the pod to maintain 
  replicas: 2 
  #template for the pods
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers: 
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: queue-release-1
  labels: 
    app: queue
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1

